server:
  port:
    8080
  forward-headers-strategy: framework

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tinkoff-practice
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true


springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs
  paths-to-match: /api/**

app:
  jwtSecret:
    asdasdasd123123supersecretkey123123123asdasdasd
